server:
  port: 8082
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://local1:8761/eureka,http://local2:8762/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: ep